version: '3.7'

services:
  k3s-dind:
    build: .
    container_name: 'k3s'
    hostname: 'k3s'
    privileged: true
    ports:
      - 8443:8443
    environment:
      - KUBECONFIG:./k3sconfig
      - K3S_API_PORT:8443
